[package]
cairo-version = "=2.9.2"
name = "tournaments"
version = "0.0.1"
edition = "2024_07"

[lib]

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["dojo::world::world_contract::world"]

[dependencies]
openzeppelin_introspection = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.18.0"}
openzeppelin_token = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.18.0"}
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.2.1" }
starknet = "2.9.2"

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.2.1" }

[features]
default = []

[profile.dev]
[profile.slot]
[profile.sepolia]
[profile.mainnet]